blueprints/guest.py
from flask_login import login_user
from flask import Blueprint, flash, render_template, redirect, url_for
from forms import RegistrationForm, LoginForm, CommentForm
from models import User, db
from werkzeug.security import generate_password_hash, check_password_hash


guest = Blueprint('guest_views', __name__, template_folder='templates', static_folder='static')


@guest.route('/register', methods=['POST','GET'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = db.session.execute(db.select(User).where(User.email == form.email.data)).scalar()
        if user:
            flash('Email already exists!')
            return redirect(url_for('login'))
        new_user = User(
            email = form.email.data,
            name = form.name.data,
            password = generate_password_hash(form.password.data, 'scrypt', 8)
        )
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        return redirect('/')
    return render_template("guest/register.html", form=form)


@guest.route('/login', methods=['POST','GET'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.execute(db.select(User).where(User.email == form.email.data)).scalar()
        if not user:
            flash("You're email does not exists")
            return redirect(url_for('login'))
        if not check_password_hash(user.password, form.password.data):
            flash('Invalid password')
            return redirect(url_for('login'))
        login_user(user)
        return redirect(url_for('user_views.get_all_posts'))
    return render_template("guest/login.html", form=form)


@guest.route("/about")
def about():
    return render_template("about.html")


@guest.route("/contact")
def contact():
    return render_template("contact.html")

blueprints/user.py
from flask_login import current_user, logout_user, login_required
from flask import Blueprint, flash, render_template, redirect, url_for, make_response, request
from forms import CreatePostForm, CommentForm, GenerateBlogForm
from models import db, BlogPost, Comment
from middleware import admin_only
import datetime as date
import requests

authenticated_user = Blueprint('user_views', __name__, template_folder='templates', static_folder='static')

@authenticated_user.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user_views.get_all_posts'))


@authenticated_user.route('/')
@login_required
def get_all_posts():
    result = db.session.execute(db.select(BlogPost))
    posts = result.scalars().all()
    return render_template("index.html", all_posts=posts)


@authenticated_user.route("/post/<int:post_id>", methods=['POST','GET'])
@login_required
def show_post(post_id):
    requested_post = db.get_or_404(BlogPost, post_id)
    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        if not current_user.is_authenticated:
            flash("You must log in first!")
            return redirect(url_for('login'))
        new_comment = Comment(
            text = comment_form.comment.data,
            comment_author = current_user,
            parent_post = requested_post
        )
        db.session.add(new_comment)
        db.session.commit()
        
        return redirect(url_for('user_views.show_post', post_id=post_id))
    return render_template("post.html", post=requested_post, comment_form=comment_form)


@authenticated_user.route("/new-post", methods=["GET", "POST"])
@login_required
@admin_only
def add_new_post():
    if request.cookies.get('body'):
        form = CreatePostForm(
            body = request.cookies.get('body'),
            title = request.cookies.get('title')
        )
    else:
        form = CreatePostForm()
    if form.validate_on_submit():
        new_post = BlogPost(
            title=form.title.data,
            subtitle=form.subtitle.data,
            body=form.body.data,
            img_url=form.img_url.data,
            author=current_user,
            date=date.datetime.today().strftime("%B %d, %Y")
        )
        db.session.add(new_post)
        db.session.commit()
        response = make_response(redirect(url_for("user_views.get_all_posts")))
        response.delete_cookie('body')
        response.delete_cookie('title')
        return response
    return render_template("make-post.html", form=form)


@authenticated_user.route("/edit-post/<int:post_id>", methods=["GET", "POST"])
@login_required
@admin_only
def edit_post(post_id):
    post = db.get_or_404(BlogPost, post_id)
    edit_form = CreatePostForm(
        title=post.title,
        subtitle=post.subtitle,
        img_url=post.img_url,
        author=post.author,
        body=post.body
    )
    if edit_form.validate_on_submit():
        post.title = edit_form.title.data
        post.subtitle = edit_form.subtitle.data
        post.img_url = edit_form.img_url.data
        post.author = current_user
        post.body = edit_form.body.data
        db.session.commit()
        return redirect(url_for("show_post", post_id=post.id))
    return render_template("make-post.html", form=edit_form, is_edit=True)


@authenticated_user.route("/delete/<int:post_id>")
@login_required
@admin_only
def delete_post(post_id):
    post_to_delete = db.get_or_404(BlogPost, post_id)
    db.session.delete(post_to_delete)
    db.session.commit()
    return redirect(url_for('get_all_posts'))


@authenticated_user.route('/generate-blog', methods=['GET','POST'])
@login_required
def generate_blog():
    form = GenerateBlogForm()
    if form.validate_on_submit():
        response = requests.get(f"http://127.0.0.1:5000{url_for('ai_routes.generate_blog', title=form.title.data)}")
        data = response.json()
        form = CreatePostForm(
            title = data["title"],
            body = data["message"]
        )
        response = redirect(url_for('user_views.add_new_post'))
        response.set_cookie('body', data["message"])
        response.set_cookie('title', data["title"])
        return response
    return render_template('generate-blog.html', form=form)

templates/about.html
{% include "header.html" %}

<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/about-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>About Me</h1>
          <span class="subheading">This is what I do.</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe
          nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis
          sit soluta odio, adipisci quas excepturi maxime quae totam ducimus
          consectetur?
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius
          praesentium recusandae illo eaque architecto error, repellendus iusto
          reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in
          officia voluptas voluptatibus, minus!
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut
          consequuntur magnam, excepturi aliquid ex itaque esse est vero natus
          quae optio aperiam soluta voluptatibus corporis atque iste neque sit
          tempora!
        </p>
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %}

templates/contact.html
{% include "header.html" %}

<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/contact-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          {% if msg_sent: %}
          <h1>Successfully sent your message</h1>
          {% else: %}
          <h1>Contact Me</h1>
          {% endif %}
          <span class="subheading">Have questions? I have answers.</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>
          Want to get in touch? Fill out the form below to send me a message and
          I will get back to you as soon as possible!
        </p>
        <div class="my-5">
          <!-- * * * * * * * * * * * * * * *-->
          <!-- * * Simplified SB Contact Form for the Tutorial* *-->
          <form
            id="contactForm"
            name="sentMessage"
            action="{{ url_for('contact') }}"
            method="post"
          >
            <div class="form-floating">
              <input
                class="form-control"
                id="name"
                name="name"
                type="text"
                placeholder="Enter your name..."
                required
              />
              <label for="name">Name</label>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                id="email"
                name="email"
                type="email"
                placeholder="Enter your email..."
                required
              />
              <label for="email">Email address</label>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                id="phone"
                name="phone"
                type="tel"
                placeholder="Enter your phone number..."
                required
              />
              <label for="phone">Phone Number</label>
            </div>
            <div class="form-floating">
              <textarea
                class="form-control"
                id="message"
                name="message"
                placeholder="Enter your message here..."
                required
                style="height: 12rem"
              ></textarea>
              <label for="message">Message</label>
            </div>
            <br />
            <button
              class="btn btn-danger text-uppercase"
              id="submitButton"
              type="submit"
            >
              NOT USED in Day 69
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %}

templates/footer.html
        <!-- Footer-->
        <footer class="border-top">
          <div class="container px-4 px-lg-5">
              <div class="row gx-4 gx-lg-5 justify-content-center">
                  <div class="col-md-10 col-lg-8 col-xl-7">
                      <ul class="list-inline text-center">
                          <li class="list-inline-item">
                              <a href="#!">
                                  <span class="fa-stack fa-lg">
                                      <i class="fas fa-circle fa-stack-2x"></i>
                                      <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                  </span>
                              </a>
                          </li>
                          <li class="list-inline-item">
                              <a href="#!">
                                  <span class="fa-stack fa-lg">
                                      <i class="fas fa-circle fa-stack-2x"></i>
                                      <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                  </span>
                              </a>
                          </li>
                          <li class="list-inline-item">
                              <a href="#!">
                                  <span class="fa-stack fa-lg">
                                      <i class="fas fa-circle fa-stack-2x"></i>
                                      <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                  </span>
                              </a>
                          </li>
                      </ul>
                      <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                  </div>
              </div>
          </div>
      </footer>
      <!-- Bootstrap core JS-->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
      <!-- Core theme JS-->
      <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
  </body>
</html>

templates/generate-blog.html
{% from "bootstrap5/form.html" import render_form %} {% block content %} 
{% include "header.html" %}

<header
  class="masthead"
  style="background-image: url('../static/assets/img/edit-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Generate Blog using AI</h1>
          <span class="subheading"
            >Let A.I. Generate your blog</span
          >
        </div>
      </div>
    </div>
  </div>
</header>

<main class="mb-4">
    <div class="container">
        <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {{render_form(form)}}
        </div>
        </div>
    </div>
</main>

{% include "footer.html" %} {% endblock %}

templates/header.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Demari's Blog</title>
    {% block styles %}
    <!-- Load Bootstrap-Flask CSS here -->
    {{ bootstrap.load_css() }}
    <link
      rel="icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='assets/favicon.ico') }}"
    />
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link
      href="{{ url_for('static', filename='css/styles.css') }}"
      rel="stylesheet"
    />
    {% endblock %}
  </head>
  <body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="/">Start Bootstrap</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto py-4 py-lg-0">
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{{ url_for('user_views.get_all_posts') }}"
                >Home</a
              >
            </li>
            <!-- TODO: Only show Login/Register if user is logged out. Otherwise show "Log Out" -->
            {% if not current_user.is_authenticated %}
              <li class="nav-item">
                <a
                  class="nav-link px-lg-3 py-3 py-lg-4"
                  href="{{ url_for('guest_views.login') }}"
                  >Login</a
                >
              </li>
              <li class="nav-item">
                <a
                  class="nav-link px-lg-3 py-3 py-lg-4"
                  href="{{ url_for('guest_views.register') }}"
                  >Register</a
                >
              </li>
            {% else %}
              <li class="nav-item">
                <a
                  class="nav-link px-lg-3 py-3 py-lg-4"
                  href="{{ url_for('user_views.logout') }}"
                  >Log Out</a
                >
              </li>
            {% endif %}
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{{ url_for('guest_views.about') }}"
                >About</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{{ url_for('guest_views.contact') }}"
                >Contact</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </body>
</html>

templates/index.html
{% include "header.html" %}

<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/home-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Demari's Blog</h1>
          <span class="subheading">A collection of random musings.</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Post preview-->
      {% for post in all_posts %}
      <div class="post-preview">
        <a href="{{ url_for('user_views.show_post', post_id=post.id) }}">
          <h2 class="post-title">{{ post.title }}</h2>
          <h3 class="post-subtitle">{{ post.subtitle }}</h3>
        </a>
        <p class="post-meta">
          Posted by
          <a href="#">{{post.author.name}}</a>
          on {{post.date}}
          {% if current_user.id == 1 %}
            <a href="{{url_for('user_views.delete_post', post_id=post.id) }}">✘</a>
          {% endif %}
        </p>
      </div>
      <!-- Divider-->
      <hr class="my-4" />
      {% endfor %}
      <!-- New Post -->
      <!-- TODO: Only show Create Post button if user id is 1 (admin user) -->
      {% if current_user.id == 1 %}
        <div class="d-flex justify-content-end mb-4">
          <a
            class="btn btn-primary float-right"
            href="{{url_for('user_views.add_new_post')}}"
            >Create New Post</a
          >
        </div>
      {% endif %}
      <!-- Pager-->
      <div class="d-flex justify-content-end mb-4">
        <a class="btn btn-secondary text-uppercase" href="#!">Older Posts →</a>
      </div>
    </div>
  </div>
</div>

{% include "footer.html" %}

templates/make-post.html
{% from "bootstrap5/form.html" import render_form %} {% block content %} {%
include "header.html" %}

<!-- Page Header -->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/edit-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          {% if is_edit: %}
          <h1>Edit Post</h1>
          {% else: %}
          <h1>New Post</h1>
          {% endif %}
          <span class="subheading"
            >You're going to make a great blog post!</span
          >
        </div>
      </div>
    </div>
  </div>
</header>

<main class="mb-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {{ ckeditor.load() }} {{ ckeditor.config(name='body') }} {{
        render_form(form, novalidate=True, button_map={"submit": "primary"}) }}
        <a href="{{url_for('user_views.generate_blog')}}">Generate using AI</a>
      </div>
    </div>
  </div>
</main>
{% include "footer.html" %} {% endblock %}

templates/post.html
{% include "header.html" %}
{% from "bootstrap5/form.html" import render_form %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('{{post.img_url}}')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="post-heading">
          <h1>{{ post.title }}</h1>
          <h2 class="subheading">{{ post.subtitle }}</h2>
          <span class="meta"
            >Posted by
            <a href="#">{{ post.author.name }}</a>
            on {{ post.date }}
          </span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        {{ post.body|safe }}
        <!--TODO: Only show Edit Post button if user id is 1 (admin user) -->
        {% if current_user.id == 1 %}
          <div class="d-flex justify-content-end mb-4">
            <a
              class="btn btn-primary float-right"
              href="{{url_for('user_views.edit_post', post_id=post.id)}}"
              >Edit Post</a
            >
          </div>
        {% endif %}
        <!-- Comments Area -->
        <!-- TODO: Add a CKEditor for commenting below -->
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='body') }}
        {{ render_form(comment_form) }}
        <div class="comment">
          <!-- TODO: Show all the comments on a post -->
          <ul class="commentList">
            {% if post.comments %}
              {% for comment in post.comments %}
                <li>
                  <div class="commenterImage">
                    <img src="{{comment.comment_author.email|gravatar}}" />
                  </div>
                  <div class="commentText">
                    <p>{{comment.text|safe}}</p>
                    <span class="date sub-text">{{comment.comment_author.name}}</span>
                  </div>
                </li>
              {% endfor %}
            {% else %}
                <li>
                  <div class="commentText">
                    <span class="date sub-text">No comment yet</span>
                  </div>
                </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</article>

{% include "footer.html" %}